trainingPartnerBatches:
 selectSqlOfBatches: > 
 select distinct B.batchId,B.batchEndDate,T.trainerName,B.totalCandidatesInBatch from batch AS B, trainer AS T,trainingPartner U where B.trainerId=T.trainerId and T.trainingPartnerId=U.trainingPartnerId and U.applicationId=: applicationId;